apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dvwa
  name: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dvwa
    spec:
      containers:
      - image: vulnerables/web-dvwa
        name: web-dvwa
