apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "nginx-policy"
    securityLog:
      enable: true
      apLogConf: "logconf"
      logDest: "syslog:server=10.105.238.128:5144"
