apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: dvwa-vs
spec:
  host: dvwa.example.com
  policies:
  - name: waf-policy
  upstreams:
  - name: dvwa 
    service: dvwa
    port: 80
  routes:
  - path: /
    action:
      pass: dvwa
