apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dvwa
  name: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - image: vulnerables/web-dvwa
        name: web-dvwa

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dvwa
  name: dvwa
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dvwa
  type: ClusterIP

---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: dvwa-vs
spec:
  host: dvwa.example.com
  #policies:
  #- name: waf-policy
  upstreams:
  - name: dvwa 
    service: dvwa
    port: 80
  routes:
  - path: /
    action:
      pass: dvwa
